### ISSUE TITLE
Adding a trope arrow causes a neverending unstopable query

### ISSUE THREAD

**Issue by MichalMed** [opendata-mvcr/ontoGrapher#160]
In Sbírka project, there is a term "zrušení textem" , which has "Typ vlastnosti" stereotype. At any time I am trying to add an arrow "má vlastnost" between "Právní akt" and "zrušení textem", rotating circle in the upper left corner never stops rotating. In graphDB appears a running query:
`PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> PREFIX owl: <http://www.w3.org/2002/07/owl#> PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> with <https://slovník.gov.cz/datový/pracovní-prostor/pojem/slovníkový-kontext/instance1779933125> delete { <https://slovník.gov.cz/datový/sbírka/pojem/právní-akt> rdfs:subClassOf ?b. ?b ?p ?o. } where { <https://slovník.gov.cz/datový/sbírka/pojem/právní-akt> rdfs:subClassOf ?b. filter(isBlank(?b)). ?b ?p ?o. }`
This query cannot be stopped and never ends. I must restart graphDB to make OG run again. If I create any other type of arrow between the same nodes, everything goes well. I was also able to create "má vlastnost" arrow between other two nodes.

**Comment by MichalMed** [comment]
even if i delete term "zrušení textem" and create it again, it behaves the same way

**Comment by MichalMed** [comment]
actually, I cannot add any new "má vlastnost" arrows out of "Právní akt"

**Comment by psiotwo** [comment]
Replicated the storage as kodi-uloziste-test and the query took .1 s to execute. I don't know where the issue is. 

I will try to run a dedicated GraphDB server for this.

**Comment by psiotwo** [comment]
The only question is whether it is running as a part of a transaction in a bunch of several queries, @bindetad ?

**Comment by bindetad** [comment]
In f6cb5b0, I tried to use a slightly different way of sending update queries (to answer your question, it has always ran as a part of a transaction). It seems to work after a few tries of the aforementioned action in the workspace. It is weird, though, that this would fix it - since in my experience, if the request is faulty, the update isn't performed in the first place. Try it out.

**Comment by MichalMed** [comment]
It also takes quite long response to pan the view of canvas. It looks like the problem has not appear now. I do not know exactly what have you done, there were two property types "účinnost textem" and "zrušení textem", I have left both without connection to "Právní akt". Now one of them was connected and the other not. I'm not sure if this is what you have done. I have a feeling that some created relations are not properly saved (even if there is "Saved" in upper left corner). I'm a little bit afraid that this issue may happen again if there will be once more a little more newly created terms at once, so I'm keeping it open for a while.

**Comment by bindetad** [comment]
I have connected the two aforementioned concepts just to test that it works. I am in the process of rigorously testing the transaction functionality for the upcoming presentation/testing to make it as bulletproof as possible.[ I have created a separate issue for the panning](#161).

**Comment by bindetad** [comment]
In #162 and #174, I have made several improvements to the process:
* Transactions are also aborted on page reload/hide. (Note that if a user hits the X button on the browser, there is no way to perform a rollback request). 
* During a transaction, the user is asked for confirmation if they want to reload the page.
* If a transaction fails due to it not being accepted server-side, the payload is logged.
* The transactions have a timeout client-side (after which a rollback is requested). I would recommend that a timeout be implemented server-side also, if there are no objections.
* Transactions have been inspected for deadlock risk - separate update queries within transactions are using separate triples.
* The amount of queries has been limited where possible.

As I have mentioned, this issue has been challenging to test and reproduce, but I have been trying a lot to check for potentially abandoned transactions, bloated requests, risks of deadlocks, etc. Since the component has been in testing for more than a week now and about 5 people are using it regularly without this issue, it seems like the risk has been reduced significantly.

**Comment by MichalMed** [comment]
ok, in that case I'm closing the issue for now
