### ISSUE TITLE
UI language changing support

### ISSUE THREAD

**Issue by bindeali** [opendata-mvcr/ontoGrapher#331]
### Current status
The language is changed based on the language of the browser (navigator.language).

### Issues

- The language cannot be changed at runtime.
- The language is dependent on the user language, which must be changed by going into the browser/OS settings. The user, therefore, cannot be set for OG only.
- For some people, this doesn't work at all (it is undesirably dependent on the users' personal configuration).

### Solution proposals
These can be used either on their own or in combination.

- The language is pulled from Keycloak.
- The language can be set in the UI (for example, in the View submenu on the Menu bar)
- The language is persisted per workspace (easily implemented) or per user (also easy, but requires intrusion into the user context or a new OG-specific context).

Request for comment @opendata-mvcr/c5-frontend-reviewers @MichalMed

**Comment by karelklima** [comment]
My two cents:
1) Language should be consistent across apps, i.e. if a user sets OntoGrapher to EN, then MissionControl should be in EN as well.
2) It should be possible to set language in all apps in some consistent manner so that the user knows where to find the settings.

One more thing - we could persist the language per device if we stored the settings in local storage. Since all apps run on the same domain, they share the local storage as well.
