### ISSUE TITLE
Make OntoGrapher compliant with workspace model

### ISSUE THREAD

**Issue by psiotwo** [opendata-mvcr/ontoGrapher#42]
Currently, packages are not bound to vocabularies - ontoGrapher considers the whole project as a vocabulary.

The desired goal is that:
- project = workspace
- top-level package = vocabulary in a workspace

This also means that each term belongs to exactly one package (no top-level terms in the package view any more).

UI changes:
- one top-level package is default (the one to which all new terms and links are saved).
- default vocabulary (top-level package) can be changed (a new action 'set as default' for each vocabulary)

**Comment by bindetad** [comment]
Progress update: I should have a reviewable version up by tomorrow. I just have a few questions to make sure I am thinking it through correctly:
* In the example, l-sgov-183-2006 should be loaded as read-only (similarly to how vsgov is loaded now) and psp-2016 should be loaded as a user-editable package with user-editable terms, correct? As determined by the ex:kodi/pouze-pro-cteni type. (Just a sanity check, so that I am sure I am not going about it completely wrong.)
* Should we combine this task with the #31 enhancement (or support of multiple stereotypes within a single element)? I see examples of terms with multiple types, such as [Flat](http://onto.fel.cvut.cz/ontologies/slovnik/datovy-psp-2016/pojem/byt) and it seems incomplete to load terms that the user should be able to edit, but can't fully.
* This is a question more towards the future: will the loading of stereotypes/relationships/packages through the [proprietary .json](https://github.com/opendata-mvcr/ontoGrapher/blob/master/src/config/Vocabularies.json) be deprecated? If so, I worry about how complicated the stereotype/relationship retrieval procedure would be. It is possible that I am overthinking it, as a straightforward way would be to find the glossary/vocabulary of a type of a term (for example, [Flat](http://onto.fel.cvut.cz/ontologies/slovnik/datovy-psp-2016/pojem/byt) has a type z-sgov-pojem:typ-objektu which is skos:inScheme z-sgov, so pull all terms which are skos:inScheme z-sgov), but I worry (perhaps unfoundedly) about unforeseen pitfalls.

**Comment by bindetad** [comment]
Progress update: as of b03724d, the following features are implemented:
* The context's vocabularies are pulled as mentioned in the previous comment, like so: 
![image](https://user-images.githubusercontent.com/56399637/79606144-706eba80-80f1-11ea-85d5-0a69e2498853.png)
* The blue background of the user-editable package signals the fact that this is a _default_ package: All new elements automatically appear in it. If the user wants to, they can set another package as default, like so (this button does not appear on read-only packages): 
![image](https://user-images.githubusercontent.com/56399637/79606313-b1ff6580-80f1-11ea-914b-261969e73b2b.png)
* The package editing modal has been slightly modified: packages now have multiple names for each language. If the package is also in the root, it corresponds to a certain vocabulary, in which case the element that reside within are skos:inScheme of that vocabulary, like so:
![image](https://user-images.githubusercontent.com/56399637/79606529-07d40d80-80f2-11ea-8f3f-ba74ed59dfaa.png)
* Elements can't reside in the root. If an action would result in no root-level packages, that action is disallowed, for example moving or deleting.

**Comment by psiotwo** [comment]
> * In the example, l-sgov-183-2006 should be loaded as read-only (similarly to how vsgov is loaded now) and psp-2016 should be loaded as a user-editable package with user-editable terms, correct? As determined by the ex:kodi/pouze-pro-cteni type. (Just a sanity check, so that I am sure I am not going about it completely wrong.)

Correct.

> * Should we combine this task with the #31 enhancement (or support of multiple stereotypes within a single element)? I see examples of terms with multiple types, such as [Flat](http://onto.fel.cvut.cz/ontologies/slovnik/datovy-psp-2016/pojem/byt) and it seems incomplete to load terms that the user should be able to edit, but can't fully.

Yes, makes sense:
- rdf:type owl:Class/owl:ObjectProperty/owl:DataProperty - should be filtered out - will never be edited by users directly.
- rdf:type skos:Concept - again, should be filtered out
- the rest is OK to edit (e.g. rdf:type | https://slovník.gov.cz/základní/pojem/mixin, rdf:type https://slovník.gov.cz/základní/pojem/typ-objektu)

> * This is a question more towards the future: will the loading of stereotypes/relationships/packages through the [proprietary .json](https://github.com/opendata-mvcr/ontoGrapher/blob/master/src/config/Vocabularies.json) be deprecated? If so, I worry about how complicated the stereotype/relationship retrieval procedure would be. It is possible that I am overthinking it, as a straightforward way would be to find the glossary/vocabulary of a type of a term (for example, [Flat](http://onto.fel.cvut.cz/ontologies/slovnik/datovy-psp-2016/pojem/byt) has a type z-sgov-pojem:typ-objektu which is skos:inScheme z-sgov, so pull all terms which are skos:inScheme z-sgov, a function which is already implemented), but I worry (perhaps unfoundedly) about unforeseen pitfalls.

- stereotypes/relationships - will be part of the 'language' and will be configurable upfront. One option is that workspace will be attached a language (e.g. selected by control panel). 
- packages - A vocabulary should have owl:imports links to the vocabularies that should be fetched.

**Comment by bindetad** [comment]
If we are extending the task to contain #31, then I would like to make a request to please extend the deadline to, say, our next meeting on Wednesday? It shouldn't be very difficult, but I want to make sure it looks right in the UI as well to allow time for you to check it and also to resolve the mixed content request issue I highlighted in an earlier comment.

**Comment by psiotwo** [comment]
checked.
