### ISSUE TITLE
Support saving Ontographer-specific data to the workspace

### ISSUE THREAD

**Issue by psiotwo** [opendata-mvcr/ontoGrapher#50]
Support storing:
- diagrams + their layout
- project settings
- other metadata which are not represented in the content context "/aktuální"
in the custom OntoGrapher context in the workspace.

**Comment by bindetad** [comment]
I should have a reviewable version up by tomorrow for this week's round of issues, I don't seem to have any significant difficulties so far. I would just like to ask a few clarifying questions:

* Does ontoGrapher's context IRI have any requirements? Haven't seen any in the docs, but I could have missed them. I am currently using http://onto.fel.cvut.cz/ontologies/application/ontoGrapher/(../). 
* What of ontoGrapher's elements' IRIs? Currently, I have them stored under http://onto.fel.cvut.cz/ontologies/application/ontoGrapher/element/[uuid], as that is the easiest to maintain, but I understand that this is not the cleanest/most correct use of IRIs, so I am prepared to use their labels (http://onto.fel.cvut.cz/ontologies/application/ontoGrapher/element/Blok for example) if needed. Intuitively, that is the more human-readable option, but I wonder if that is necessary in an application-specific context.

**Comment by psiotwo** [comment]
context - yes, OK for now
elements - the model objects should have a namespace of the respective vocabulary - e.g. https://slovník.gov.cz/legislativní/sbírka/111/2009/pojem/osoba for the term "osoba" in the legislation vocabulary of the law "111/2009", as shown in https://opendata.gov.cz/_media/dokumenty:s%C3%A9mantick%C3%BD-slovn%C3%ADk-pojm%C5%AF:c1v2d1_n%C3%A1vrh_koncepce_s%C3%A9mantick%C3%A9ho_slovn%C3%ADku_pojm%C5%AF.pdf

The particular graph elements might be arbitrary, but I propose to have the IRIs like:
<MODEL-OBJECT-IRI>/<DIAGRAM-ID>, e.g.
https://slovník.gov.cz/legislativní/sbírka/111/2009/pojem/osoba/diagram-1

**Comment by bindetad** [comment]
I am very sorry, but unfortunately I won't be able to push a master branch-worthy version today. The reason is that I have run into obstacles that are not difficult, but will take time to overcome -- I suspect till Thursday at the latest (I won't be able to work on it on Tuesday). 

### **Here's what I have implemented so far in 06f330e:**

- Fixes for #47, #48
- Removal of "Save" button in Detail Panel, any changes are now saved (or attempted to be saved, more on this below) as soon as a change occurs
- Implementation of saving: skos:prefLabel, rdf:type, skos:definition, any connections to other objects (in other words, the ontological model as described [here](https://opendata.gov.cz/_media/dokumenty:s%C3%A9mantick%C3%BD-slovn%C3%ADk-pojm%C5%AF:c1v2d1_n%C3%A1vrh_koncepce_s%C3%A9mantick%C3%A9ho_slovn%C3%ADku_pojm%C5%AF.pdf)
- Saving is implemented transactionally (the user is notified of any connection to the DB on the menu panel) 
- If saving does not happen for any reason, the user is notified along with a prompt to retry the transaction
- ontoGrapher specific data is also saved, as described below

This means that I will be able to show a basic demo of this working on Wednesday, but not in the full capacity that this functionality is supposed to have.

### **What is currently missing:**
- Fixes for bugs (mostly in the realm of assigning IRIs correctly and assuring that no outdated/residual triples are removed from the store)
- Correcting ontoGrapher specific data structure
- Correctly handling newly created vocabularies

### **ontoGrapher-specific triples**
I would like to hear any comments you have on the design, but I know that it is a lot of information -- so if you want to look at it in another medium, let me know. I anticipate that the most relevant topic of conversation will again be the IRIs that the data is under.

This is perhaps best explained on an example:
@prefix og: <http://onto.fel.cvut.cz/ontologies/application/ontoGrapher/> .
http://onto.fel.cvut.cz/ontologies/slovnik/datovy-psp-2016/pojem/byt
has after saving the following associated resources:

http://onto.fel.cvut.cz/ontologies/slovnik/datovy-psp-2016/pojem/byt/diagram
This is where information that is the same across all diagrams is located:
[og:id](https://github.com/opendata-mvcr/ontoGrapher/blob/06f330e2a17b31f7373a3ed99ff27e89c97ae361/src/config/Variables.tsx#L15), [og:untitled](https://github.com/opendata-mvcr/ontoGrapher/blob/06f330e2a17b31f7373a3ed99ff27e89c97ae361/src/config/Variables.tsx#L21), [og:active](https://github.com/opendata-mvcr/ontoGrapher/blob/06f330e2a17b31f7373a3ed99ff27e89c97ae361/src/config/Variables.tsx#L33)
The og:attributes and og:properties are also saved here, but as references to
http://onto.fel.cvut.cz/ontologies/slovnik/datovy-psp-2016/pojem/byt/(attribute/property)-[index]
(example: byt/attribute-1), which have og:attribute-name and og:attribute-type.
http://onto.fel.cvut.cz/ontologies/slovnik/datovy-psp-2016/pojem/byt/diagram-[index] is used for diagram specific data (example: byt/diagram-1 for the diagram of the first index). The predicates used here are as follows: [og:position-x](https://github.com/opendata-mvcr/ontoGrapher/blob/06f330e2a17b31f7373a3ed99ff27e89c97ae361/src/config/Variables.tsx#L31), [og:position-y](https://github.com/opendata-mvcr/ontoGrapher/blob/06f330e2a17b31f7373a3ed99ff27e89c97ae361/src/config/Variables.tsx#313), [og:hidden](https://github.com/opendata-mvcr/ontoGrapher/blob/06f330e2a17b31f7373a3ed99ff27e89c97ae361/src/config/Variables.tsx#L29).

**Project Settings**
Most of these are derived from the context, so they don't need to be saved, the exceptions being og:selected[Diagram/Package/Language/Link]. 
All of this information has the context (og) as predicate, except for packages, which are under og:package/[Package name] and diagrams, which are under og:diagram-[index].

**Context**
The context itself is handled the expected way as a d-sgov-pracovní-prostor-pojem:aplikační-kontext that is appended to the context IRI (:metadata-kontext-123 in this example).

**New vocabularies**
New vocabularies are planned to look the same as the others in the context (in accordance with the aforementioned [document](https://opendata.gov.cz/_media/dokumenty:s%C3%A9mantick%C3%BD-slovn%C3%ADk-pojm%C5%AF:c1v2d1_n%C3%A1vrh_koncepce_s%C3%A9mantick%C3%A9ho_slovn%C3%ADku_pojm%C5%AF.pdf)) with a /model, /glossary, /diagram, rdfs:label, ConceptScheme and Ontology types, and imports. based on the root-level packages. What I probably can't add at this stage is provenance data and versioning.

**Comment by bindetad** [comment]
In 8ee5c42, this is implemented as follows:
* for elements (boxes), the usual IRI (ex. ...pojem/Blok) is enriched with an additional object (ex:pojem/Blok/diagram) with ontoGrapher-specific information.
* for links, the ontological connection is saved in #49. ontoGrapher-specific information about the links is saved in the special ontoGrapher graph (http://onto.fel.cvut.cz/ontologies/application/ontoGrapher/).
* speaking of which, the project settings are also saved there.

**Comment by psiotwo** [comment]
Multiple forward slashes prevent the workspace from saving, ending with 500, e.g. for request


https://onto.fel.cvut.cz:7200**//**repositories/kodi-pracovni-prostor-validace?query=PREFIX%20owl%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F2002%2F07%2Fowl%23%3E%20PREFIX%20skos%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F2004%2F02%2Fskos%2Fcore%23%3E%20PREFIX%20rdfs%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F2000%2F01%2Frdf-schema%23%3E%20select%20%3Fvocab%20(bound(%3Fro)%20as%20%3FreadOnly)%20%3FlabelVocab%20%3Flabel%20%3FvocabIRI%20%3Fimport%20%3FimportType%20where%20%7B%20BIND(%3Chttp%3A%2F%2Fexample.org%2Fpracovni-prostor%2Fmetadatov%C3%BD-kontext-123%3E%20as%20%3FcontextIRI)%20.%20%3FcontextIRI%20rdfs%3Alabel%20%3Flabel%3B%20%3Chttps%3A%2F%2Fslovn%C3%ADk.gov.cz%2Fdatov%C3%BD%2Fpracovn%C3%AD-prostor%2Fpojem%2Fodkazuje-na-kontext%3E%20%3Fvocab.%20%3Fvocab%20a%20%3FvocabType%20.%20VALUES%20%3FvocabType%20%7B%20%3Chttps%3A%2F%2Fslovn%C3%ADk.gov.cz%2Fdatov%C3%BD%2Fpracovn%C3%AD-prostor%2Fpojem%2Fslovn%C3%ADkov%C3%BD-kontext%3E%20%3Chttps%3A%2F%2Fslovn%C3%ADk.gov.cz%2Fdatov%C3%BD%2Fpracovn%C3%AD-prostor%2Fpojem%2Fslovn%C3%ADkov%C3%BD-kontext-pouze-pro-%C4%8Dten%C3%AD%3E%20%7D%20%3Fvocab%20%3Chttps%3A%2F%2Fslovn%C3%ADk.gov.cz%2Fdatov%C3%BD%2Fpracovn%C3%AD-prostor%2Fpojem%2Fobsahuje-slovn%C3%ADk%3E%20%3FvocabIRI%20.%20%3FvocabIRI%20owl%3Aimports%20%3Fimport%20.%20%3Fimport%20a%20%3FimportType%20.%20%3Fimport%20rdfs%3Alabel%20%3FlabelVocab.%20OPTIONAL%7B%20%3Fvocab%20a%20%20%3Fro%20.%20FILTER(%3Fro%20%3D%20%3Chttps%3A%2F%2Fslovn%C3%ADk.gov.cz%2Fdatov%C3%BD%2Fpracovn%C3%AD-prostor%2Fpojem%2Fslovn%C3%ADkov%C3%BD-kontext-pouze-pro-%C4%8Dten%C3%AD%3E)%20.%20%20%7D%20%7D

**Comment by bindetad** [comment]
Seems to be fixed in b317f60. If you get any further save errors, please describe the action performed right before along with the request, it helps a great deal. Also, the changelog lists the actions that trigger saving, if you want to take a look.

**Comment by bindetad** [comment]
Here's a description of the exact problem I'm having: To start a transaction, I need to use [this endpoint (swagger description)](https://onto.fel.cvut.cz:7200/v/8.10.1/res/swagger/index.html#!/transactions/post_repositories_repositoryID_transactions). The response should look as follows (note the `location` header - this is what I need to know where to send the individual transaction commands.)
![image](https://user-images.githubusercontent.com/56399637/81722594-e44a7b80-9481-11ea-90fb-1087c9dea231.png)

However, Javascript only returns seven default headers in CORS mode, as described [here](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Expose-Headers); `location` is not one of them.

I have modified the transaction ID request function locally from fetch to XMLHTTPRequest to make this clearer: the first message is `xhttp.getAllResponseHeaders()`, the second is the result of calling `xhttp.getResponseHeader('Location')`: 
![image](https://user-images.githubusercontent.com/56399637/81723050-8d917180-9482-11ea-9c2c-11125d58a4c2.png)
