### ISSUE TITLE
Implement FULL OWL (de-)serialization of models to workspace

### ISSUE THREAD

**Issue by psiotwo** [opendata-mvcr/ontoGrapher#52]
Adjust current (de)-serialization to support 
- loading FULL representation of models from workspace.
- storing FULL representation of models to workspace.

This means loading domains/ranges as shown https://xn--slovnk-7va.gov.cz/describe/?url=nodeID%3A%2F%2Fb52020

**Comment by bindetad** [comment]
The aforementioned representation of models is supported as of 3ec1a99. Example:
![image](https://user-images.githubusercontent.com/56399637/82163246-3b00ec80-98aa-11ea-8921-8e091942e527.png)
Storing looks as follows:
![image](https://user-images.githubusercontent.com/56399637/82163266-5b30ab80-98aa-11ea-9f3d-8431f885bc1b.png)
You may notice that the restrictions now have IRIs instead of being represented as blank nodes. This is because skolemization of blank nodes from JSON-LD structures (which I use to build the data that is sent) does not generate unique IRIs, and therefore all previously saved restrictions would be overwritten on each update. It does not affect loading these restrictions back in any way.

**Comment by ledsoft** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Implementace podpory otevírání pracovního prostoru v TermIt](https://trello.com/c/AfdOfzHE/155-implementace-podpory-otev%C3%ADr%C3%A1n%C3%AD-pracovn%C3%ADho-prostoru-v-termit)
