### ISSUE TITLE
Non-imported stereotypes from Z-SGoV

### ISSUE THREAD

**Issue by martinnec** [opendata-mvcr/ontoGrapher#9]
There are some stereotypes missing for some concepts from Z-SGoV:

https://slovník.gov.cz/základní/pojem/má-vztažený-prvek-1
https://slovník.gov.cz/základní/pojem/má-vztažený-prvek-2

Is it because their definition is incomplete? They do not have name. They are subproperties so that they inherit features from https://slovník.gov.cz/základní/pojem/má-vztažený-prvek.

**Comment by bindetad** [comment]
They are currently not imported due to the fact that they are not inScheme of Z-SGoV. I must have missed them since I based my completing of the task of importing all elements on [the list in the semantic browser](https://xn--slovnk-7va.gov.cz/prohl%C3%AD%C5%BEe%C4%8D/#!?facets=%7B%22glosar%22:%7B%22value%22:%22%3Chttps:%2F%2Fslovn%C3%ADk.gov.cz%2Fz%C3%A1kladn%C3%AD%2Fglos%C3%A1%C5%99%3E%22,%22constraint%22:%22%20%3Fid%20%3Chttp:%2F%2Fwww.w3.org%2F2004%2F02%2Fskos%2Fcore%23inScheme%3E%20%3Chttps:%2F%2Fslovn%C3%ADk.gov.cz%2Fz%C3%A1kladn%C3%AD%2Fglos%C3%A1%C5%99%3E%20.%20%22%7D%7D). Should I modify the importer logic so that all subProperties and subClasses are also imported?

**Comment by martinnec** [comment]
Yes

**Comment by bindetad** [comment]
Fixed in 0ece3681344b6b4277af4d73b9dfe870f0cb09eb, closing.

**Comment by martinnec** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Práce na issues v ontroGrapher #2](https://trello.com/c/jjYcBXyE/65-pr%C3%A1ce-na-issues-v-ontrographer-2)

**Comment by blcham** [comment]
checked.
